[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = [
  "ex01_variables_conditions/tests",
  "ex02_boucles_listes_dictionaire/tests",
  "ex03_fonctions_algo/tests",
  "ex04_tri/tests",
  "ex05_arbre_parcours/tests",
  "ex06_voyageur_commerce/tests"
]
addopts = "-q"
